title: Sentimentanalyse Notebooks

execute:
  execute_notebooks: off

launch_buttons:
  thebe: true
  binderhub_url: https://mybinder.org

repository:
  url: https://github.com/apawlik/sentimentanalyse_notebooks
  branch: main

html:
  use_repository_button: true
  use_issues_button: true
